CFLAGS+=-O -D_MINIX -D_POSIX_SOURCE -D__USG

SRCS =  \
	asyn_cancel.c \
	asyn_close.c \
	asyn_init.c \
	asyn_pending.c \
	asyn_read.c \
	asyn_synch.c \
	asyn_wait.c \
	asyn_write.c

BUILD_DIR = $(LIB_BUILD_ROOT)/libc/asyn
include $(ROOT)/lib/Makefile.inc
