# Makefile for Reincarnation Server (RS)
TARGETS := rs

OBJS-rs := exec.o main.o request.o manager.o table.o utility.o memory.o error.o

STACK_SIZE-rs := 8125k

LIBS += -lexec

include $(ROOT)/servers/Makefile.inc
