# Makefile for libutil
CFLAGS+=-O -D_MINIX -D_POSIX_SOURCE

SRCS=	openpty.c sha2.c efun.c \
		sha1.c sha1hl.c sha2.c sha2hl.c md5c.c md5hl.c

BUILD_DIR = $(LIB_BUILD_ROOT)/libutil
include $(ROOT)/lib/Makefile.inc
