# Makefile for lib/math.

CFLAGS+=-O -D_MINIX -D_POSIX_SOURCE


SRCS= \
	asin.c \
	atan.c \
	atan2.c \
	ceil.c \
	compare.c \
	exp.c \
	fabs.c \
	floor.c \
	fmod.c \
	hugeval.c \
	log.c \
	log10.c \
	pow.c \
	s_rint.c \
	scalbn.c \
	sin.c \
	sinh.c \
	sqrt.c \
	tan.c \
	tanh.c

BUILD_DIR = $(LIB_BUILD_ROOT)/libc/math
include $(ROOT)/lib/Makefile.inc
