CFLAGS+=-O -D_MINIX -D_POSIX_SOURCE

SRCS+=  \
	towupper.c \
	towlower.c \
	wcscasecmp.c \
	wcscat.c \
	wcschr.c \
	wcscmp.c \
	wcscpy.c \
	wcscspn.c \
	wcsdup.c \
	wcslcat.c \
	wcslcpy.c \
	wcslen.c \
	wcsncasecmp.c \
	wcsncat.c \
	wcsncmp.c \
	wcsncpy.c \
	wcspbrk.c \
	wcsrchr.c \
	wcsspn.c \
	wcsstr.c \
	wcstok.c \
	wcstombs.c \
	wcswcs.c \
	wctomb.c \
	wmemchr.c \
	wmemcmp.c \
	wmemcpy.c \
	wmemmove.c \
	wmemset.c
		
BUILD_DIR = $(LIB_BUILD_ROOT)/libc/wchar
include $(ROOT)/lib/Makefile.inc
