# Makefile for Process Manager (PM)
TARGETS := pm

OBJS-pm := main.o forkexit.o break.o exec.o time.o alarm.o \
	signal.o utility.o table.o trace.o getset.o misc.o \
	profile.o dma.o mcontext.o schedule.o

LIBS += -ltimers

include ../Makefile.inc
